image: node:18

stages:
  - install
  - test
  - build

cache:
  paths:
    - React/Monprojet/node_modules/

install_dependencies:
  stage: install
  script:
    - cd React/Monprojet
    - npm install
  artifacts:
    paths:
      - React/Monprojet/node_modules/
    expire_in: 1 hour

test:
  stage: test
  dependencies:
    - install_dependencies
  script:
    - cd Monprojet
    - npm run test:run
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build:
  stage: build
  dependencies:
    - install_dependencies
  script:
    - cd Monprojet
    - npm run build
  artifacts:
    paths:
      - Monprojet/dist/
    expire_in: 1 week
  only:
    - main